version: '3'
services:
  bot:
    image: node:latest
    container_name: bot-node
    stdin_open: true
    tty: true
    command: bash -c "npm install && npm start"
    volumes:
      - .:/app
    environment:
      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
    working_dir: /app